HYPHY_DIR=$1
LIB_PATH=$HYPHY_DIR/res
BATCH_FILE_PATH=$HYPHY_DIR/res/TemplateBatchFiles/SelectionAnalyses/FEL.bf
DATA_PATH=$2
TREE_PATH=$3
GENETIC_CODE=$4
SYN_RATE_VARIATION=$5
(echo $GENETIC_CODE; echo $DATA_PATH; echo $TREE_PATH; echo 5; echo $SYN_RATE_VARIATION;) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH
