HYPHY_DIR=$1
LIB_PATH=$HYPHY_DIR/res
BATCH_FILE_PATH=$HYPHY_DIR/res/TemplateBatchFiles/SelectionAnalyses/FEL.bf
DATA_PATH=$2
TREE_PATH=$3
SELECT_FOREGROUND_BRANCHES='5'
GENETIC_CODE=$4
SYN_RATE_VARIATION=$5
PVALUETHRESHOLD='0.1'


GETCOUNT=$HYPHY_DIR/../src/helpers/bfs/getAnnotatedCount.bf

output=$(echo $TREE_PATH | $HYPHY_DIR/HYPHYMP $GETCOUNT)
count=$(echo "${output: -1}")

if [ $count -eq 2 ]
then
  echo "(echo '$GENETIC_CODE'; echo '$DATA_PATH'; echo '$TREE_PATH'; echo 5; echo '$SYN_RATE_VARIATION'; echo '$PVALUETHRESHOLD';) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH"
  (echo $GENETIC_CODE; echo $DATA_PATH; echo $TREE_PATH; echo 5; echo $SYN_RATE_VARIATION; echo $PVALUETHRESHOLD;) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH
else
  echo "(echo '$GENETIC_CODE'; echo '$DATA_PATH'; echo '$TREE_PATH'; echo 4; echo '$SYN_RATE_VARIATION'; echo '$PVALUETHRESHOLD';) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH"
  (echo $GENETIC_CODE; echo $DATA_PATH; echo $TREE_PATH; echo 4; echo $SYN_RATE_VARIATION; echo $PVALUETHRESHOLD;) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH
fi
