HYPHY_DIR=$1
LIB_PATH=$HYPHY_DIR/res
BATCH_FILE_PATH=$HYPHY_DIR/res/TemplateBatchFiles/GARD.bf
DATA_PATH=$2
GENETIC_CODE=$3
SITE_RATE_VARIATION=$4
NUM_RATE_CLASSES=$5
(echo $GENETIC_CODE; echo $DATA_PATH; echo 3; echo 1; echo $SITE_RATE_VARIATION; echo $NUM_RATE_CLASSES:) | $HYPHY_DIR/HYPHYMPI LIBPATH=$LIB_PATH $BATCH_FILE_PATH
