HYPHY_DIR=$1
LIB_PATH=$HYPHY_DIR/res
BATCH_FILE_PATH=$HYPHY_DIR/res/TemplateBatchFiles/SelectionAnalyses/RELAX.bf
DATA_PATH=$2
TREE_PATH=$3
GENETIC_CODE=$4
ANALYSIS_TYPE=$5

(echo $GENETIC_CODE; echo $DATA_PATH; echo $TREE_PATH; echo 3; echo 2; echo $ANALYSIS_TYPE;) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH
