HYPHY_DIR=$1
LIB_PATH=$HYPHY_DIR/res
BATCH_FILE_PATH=$HYPHY_DIR/res/TemplateBatchFiles/SelectionAnalyses/RELAX.bf
DATA_PATH=$2
GENETIC_CODE=$3
ANALYSIS_TYPE=$4
(echo $GENETIC_CODE; echo $DATA_PATH; echo 3; echo 1; echo $ANALYSIS_TYPE;) | $HYPHY_DIR/HYPHYMP LIBPATH=$LIB_PATH $BATCH_FILE_PATH
